layout_spectrum: 0.1039427
color:
  saturation: 0.895786
  brandStrength: 0.5798007
  lightness: 0.8064516
  rhythmicContrast: 0.5377988
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.8978494
name: Tom Borgers
